language: node_js
sudo: required
node_js:
  - 'stable'
before_script:
  - npm install -g bower polylint web-component-tester
  - bower install
script:
  - xvfb-run wct
  - "if [ \"${TRAVIS_PULL_REQUEST}\" = \"false\" ]; then wct -s 'default'; fi"