language: node_js
sudo: false
node_js:
  - 'iojs'
  - '0.10'
  - '0.12'
  - '4'
  - '5'
before_script:
  - npm install
  - bower install
script:
  - xvfb-run wct
  - "if [ \"${TRAVIS_PULL_REQUEST}\" = \"false\" ]; then wct -s 'default'; fi"